name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          filename: github-metrics.svg
          user: selinakk

          template: classic
          base: header, activity

          plugin_activity: yes
          plugin_activity_filter: push
          plugin_activity_days: 365
          plugin_activity_limit: 1

          plugin_languages: yes
          plugin_languages_limit: 5
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_indepth: yes

          plugin_streak: yes
          plugin_followup: no
          plugin_licenses: no
          plugin_sponsors: no

          config_theme: github_dark
          config_display: large
